// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: otpauth-migration.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from otpauth-migration.proto</summary>
public static partial class OtpauthMigrationReflection {

  #region Descriptor
  /// <summary>File descriptor for otpauth-migration.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static OtpauthMigrationReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdvdHBhdXRoLW1pZ3JhdGlvbi5wcm90byLfBAoHUGF5bG9hZBIuCg5vdHBf",
          "cGFyYW1ldGVycxgBIAMoCzIWLlBheWxvYWQuT3RwUGFyYW1ldGVycxIPCgd2",
          "ZXJzaW9uGAIgASgFEhIKCmJhdGNoX3NpemUYAyABKAUSEwoLYmF0Y2hfaW5k",
          "ZXgYBCABKAUSEAoIYmF0Y2hfaWQYBSABKAUaugEKDU90cFBhcmFtZXRlcnMS",
          "DgoGc2VjcmV0GAEgASgMEgwKBG5hbWUYAiABKAkSDgoGaXNzdWVyGAMgASgJ",
          "EiUKCWFsZ29yaXRobRgEIAEoDjISLlBheWxvYWQuQWxnb3JpdGhtEiMKBmRp",
          "Z2l0cxgFIAEoDjITLlBheWxvYWQuRGlnaXRDb3VudBIeCgR0eXBlGAYgASgO",
          "MhAuUGF5bG9hZC5PdHBUeXBlEg8KB2NvdW50ZXIYByABKAMieQoJQWxnb3Jp",
          "dGhtEhkKFUFMR09SSVRITV9VTlNQRUNJRklFRBAAEhIKDkFMR09SSVRITV9T",
          "SEExEAESFAoQQUxHT1JJVEhNX1NIQTI1NhACEhQKEEFMR09SSVRITV9TSEE1",
          "MTIQAxIRCg1BTEdPUklUSE1fTUQ1EAQiVQoKRGlnaXRDb3VudBIbChdESUdJ",
          "VF9DT1VOVF9VTlNQRUNJRklFRBAAEhMKD0RJR0lUX0NPVU5UX1NJWBABEhUK",
          "EURJR0lUX0NPVU5UX0VJR0hUEAIiSQoHT3RwVHlwZRIYChRPVFBfVFlQRV9V",
          "TlNQRUNJRklFRBAAEhEKDU9UUF9UWVBFX0hPVFAQARIRCg1PVFBfVFlQRV9U",
          "T1RQEAI="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Payload), global::Payload.Parser, new[]{ "OtpParameters", "Version", "BatchSize", "BatchIndex", "BatchId" }, null, new[]{ typeof(global::Payload.Types.Algorithm), typeof(global::Payload.Types.DigitCount), typeof(global::Payload.Types.OtpType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Payload.Types.OtpParameters), global::Payload.Types.OtpParameters.Parser, new[]{ "Secret", "Name", "Issuer", "Algorithm", "Digits", "Type", "Counter" }, null, null, null, null)})
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Payload : pb::IMessage<Payload>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Payload> _parser = new pb::MessageParser<Payload>(() => new Payload());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Payload> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::OtpauthMigrationReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Payload() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Payload(Payload other) : this() {
    _hasBits0 = other._hasBits0;
    otpParameters_ = other.otpParameters_.Clone();
    version_ = other.version_;
    batchSize_ = other.batchSize_;
    batchIndex_ = other.batchIndex_;
    batchId_ = other.batchId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Payload Clone() {
    return new Payload(this);
  }

  /// <summary>Field number for the "otp_parameters" field.</summary>
  public const int OtpParametersFieldNumber = 1;
  private static readonly pb::FieldCodec<global::Payload.Types.OtpParameters> _repeated_otpParameters_codec
      = pb::FieldCodec.ForMessage(10, global::Payload.Types.OtpParameters.Parser);
  private readonly pbc::RepeatedField<global::Payload.Types.OtpParameters> otpParameters_ = new pbc::RepeatedField<global::Payload.Types.OtpParameters>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Payload.Types.OtpParameters> OtpParameters {
    get { return otpParameters_; }
  }

  /// <summary>Field number for the "version" field.</summary>
  public const int VersionFieldNumber = 2;
  private readonly static int VersionDefaultValue = 0;

  private int version_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Version {
    get { if ((_hasBits0 & 1) != 0) { return version_; } else { return VersionDefaultValue; } }
    set {
      _hasBits0 |= 1;
      version_ = value;
    }
  }
  /// <summary>Gets whether the "version" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasVersion {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "version" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearVersion() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "batch_size" field.</summary>
  public const int BatchSizeFieldNumber = 3;
  private readonly static int BatchSizeDefaultValue = 0;

  private int batchSize_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BatchSize {
    get { if ((_hasBits0 & 2) != 0) { return batchSize_; } else { return BatchSizeDefaultValue; } }
    set {
      _hasBits0 |= 2;
      batchSize_ = value;
    }
  }
  /// <summary>Gets whether the "batch_size" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasBatchSize {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "batch_size" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearBatchSize() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "batch_index" field.</summary>
  public const int BatchIndexFieldNumber = 4;
  private readonly static int BatchIndexDefaultValue = 0;

  private int batchIndex_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BatchIndex {
    get { if ((_hasBits0 & 4) != 0) { return batchIndex_; } else { return BatchIndexDefaultValue; } }
    set {
      _hasBits0 |= 4;
      batchIndex_ = value;
    }
  }
  /// <summary>Gets whether the "batch_index" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasBatchIndex {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "batch_index" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearBatchIndex() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "batch_id" field.</summary>
  public const int BatchIdFieldNumber = 5;
  private readonly static int BatchIdDefaultValue = 0;

  private int batchId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BatchId {
    get { if ((_hasBits0 & 8) != 0) { return batchId_; } else { return BatchIdDefaultValue; } }
    set {
      _hasBits0 |= 8;
      batchId_ = value;
    }
  }
  /// <summary>Gets whether the "batch_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasBatchId {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "batch_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearBatchId() {
    _hasBits0 &= ~8;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Payload);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Payload other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!otpParameters_.Equals(other.otpParameters_)) return false;
    if (Version != other.Version) return false;
    if (BatchSize != other.BatchSize) return false;
    if (BatchIndex != other.BatchIndex) return false;
    if (BatchId != other.BatchId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= otpParameters_.GetHashCode();
    if (HasVersion) hash ^= Version.GetHashCode();
    if (HasBatchSize) hash ^= BatchSize.GetHashCode();
    if (HasBatchIndex) hash ^= BatchIndex.GetHashCode();
    if (HasBatchId) hash ^= BatchId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    otpParameters_.WriteTo(output, _repeated_otpParameters_codec);
    if (HasVersion) {
      output.WriteRawTag(16);
      output.WriteInt32(Version);
    }
    if (HasBatchSize) {
      output.WriteRawTag(24);
      output.WriteInt32(BatchSize);
    }
    if (HasBatchIndex) {
      output.WriteRawTag(32);
      output.WriteInt32(BatchIndex);
    }
    if (HasBatchId) {
      output.WriteRawTag(40);
      output.WriteInt32(BatchId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    otpParameters_.WriteTo(ref output, _repeated_otpParameters_codec);
    if (HasVersion) {
      output.WriteRawTag(16);
      output.WriteInt32(Version);
    }
    if (HasBatchSize) {
      output.WriteRawTag(24);
      output.WriteInt32(BatchSize);
    }
    if (HasBatchIndex) {
      output.WriteRawTag(32);
      output.WriteInt32(BatchIndex);
    }
    if (HasBatchId) {
      output.WriteRawTag(40);
      output.WriteInt32(BatchId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += otpParameters_.CalculateSize(_repeated_otpParameters_codec);
    if (HasVersion) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
    }
    if (HasBatchSize) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BatchSize);
    }
    if (HasBatchIndex) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BatchIndex);
    }
    if (HasBatchId) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BatchId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Payload other) {
    if (other == null) {
      return;
    }
    otpParameters_.Add(other.otpParameters_);
    if (other.HasVersion) {
      Version = other.Version;
    }
    if (other.HasBatchSize) {
      BatchSize = other.BatchSize;
    }
    if (other.HasBatchIndex) {
      BatchIndex = other.BatchIndex;
    }
    if (other.HasBatchId) {
      BatchId = other.BatchId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          otpParameters_.AddEntriesFrom(input, _repeated_otpParameters_codec);
          break;
        }
        case 16: {
          Version = input.ReadInt32();
          break;
        }
        case 24: {
          BatchSize = input.ReadInt32();
          break;
        }
        case 32: {
          BatchIndex = input.ReadInt32();
          break;
        }
        case 40: {
          BatchId = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          otpParameters_.AddEntriesFrom(ref input, _repeated_otpParameters_codec);
          break;
        }
        case 16: {
          Version = input.ReadInt32();
          break;
        }
        case 24: {
          BatchSize = input.ReadInt32();
          break;
        }
        case 32: {
          BatchIndex = input.ReadInt32();
          break;
        }
        case 40: {
          BatchId = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Payload message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Algorithm {
      [pbr::OriginalName("ALGORITHM_UNSPECIFIED")] Unspecified = 0,
      [pbr::OriginalName("ALGORITHM_SHA1")] Sha1 = 1,
      [pbr::OriginalName("ALGORITHM_SHA256")] Sha256 = 2,
      [pbr::OriginalName("ALGORITHM_SHA512")] Sha512 = 3,
      [pbr::OriginalName("ALGORITHM_MD5")] Md5 = 4,
    }

    public enum DigitCount {
      [pbr::OriginalName("DIGIT_COUNT_UNSPECIFIED")] Unspecified = 0,
      [pbr::OriginalName("DIGIT_COUNT_SIX")] Six = 1,
      [pbr::OriginalName("DIGIT_COUNT_EIGHT")] Eight = 2,
    }

    public enum OtpType {
      [pbr::OriginalName("OTP_TYPE_UNSPECIFIED")] Unspecified = 0,
      [pbr::OriginalName("OTP_TYPE_HOTP")] Hotp = 1,
      [pbr::OriginalName("OTP_TYPE_TOTP")] Totp = 2,
    }

    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class OtpParameters : pb::IMessage<OtpParameters>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<OtpParameters> _parser = new pb::MessageParser<OtpParameters>(() => new OtpParameters());
      private pb::UnknownFieldSet _unknownFields;
      private int _hasBits0;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<OtpParameters> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::Payload.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public OtpParameters() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public OtpParameters(OtpParameters other) : this() {
        _hasBits0 = other._hasBits0;
        secret_ = other.secret_;
        name_ = other.name_;
        issuer_ = other.issuer_;
        algorithm_ = other.algorithm_;
        digits_ = other.digits_;
        type_ = other.type_;
        counter_ = other.counter_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public OtpParameters Clone() {
        return new OtpParameters(this);
      }

      /// <summary>Field number for the "secret" field.</summary>
      public const int SecretFieldNumber = 1;
      private readonly static pb::ByteString SecretDefaultValue = pb::ByteString.Empty;

      private pb::ByteString secret_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pb::ByteString Secret {
        get { return secret_ ?? SecretDefaultValue; }
        set {
          secret_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }
      /// <summary>Gets whether the "secret" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasSecret {
        get { return secret_ != null; }
      }
      /// <summary>Clears the value of the "secret" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearSecret() {
        secret_ = null;
      }

      /// <summary>Field number for the "name" field.</summary>
      public const int NameFieldNumber = 2;
      private readonly static string NameDefaultValue = "";

      private string name_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string Name {
        get { return name_ ?? NameDefaultValue; }
        set {
          name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }
      /// <summary>Gets whether the "name" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasName {
        get { return name_ != null; }
      }
      /// <summary>Clears the value of the "name" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearName() {
        name_ = null;
      }

      /// <summary>Field number for the "issuer" field.</summary>
      public const int IssuerFieldNumber = 3;
      private readonly static string IssuerDefaultValue = "";

      private string issuer_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string Issuer {
        get { return issuer_ ?? IssuerDefaultValue; }
        set {
          issuer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }
      /// <summary>Gets whether the "issuer" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasIssuer {
        get { return issuer_ != null; }
      }
      /// <summary>Clears the value of the "issuer" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearIssuer() {
        issuer_ = null;
      }

      /// <summary>Field number for the "algorithm" field.</summary>
      public const int AlgorithmFieldNumber = 4;
      private readonly static global::Payload.Types.Algorithm AlgorithmDefaultValue = global::Payload.Types.Algorithm.Unspecified;

      private global::Payload.Types.Algorithm algorithm_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::Payload.Types.Algorithm Algorithm {
        get { if ((_hasBits0 & 1) != 0) { return algorithm_; } else { return AlgorithmDefaultValue; } }
        set {
          _hasBits0 |= 1;
          algorithm_ = value;
        }
      }
      /// <summary>Gets whether the "algorithm" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasAlgorithm {
        get { return (_hasBits0 & 1) != 0; }
      }
      /// <summary>Clears the value of the "algorithm" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearAlgorithm() {
        _hasBits0 &= ~1;
      }

      /// <summary>Field number for the "digits" field.</summary>
      public const int DigitsFieldNumber = 5;
      private readonly static global::Payload.Types.DigitCount DigitsDefaultValue = global::Payload.Types.DigitCount.Unspecified;

      private global::Payload.Types.DigitCount digits_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::Payload.Types.DigitCount Digits {
        get { if ((_hasBits0 & 2) != 0) { return digits_; } else { return DigitsDefaultValue; } }
        set {
          _hasBits0 |= 2;
          digits_ = value;
        }
      }
      /// <summary>Gets whether the "digits" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasDigits {
        get { return (_hasBits0 & 2) != 0; }
      }
      /// <summary>Clears the value of the "digits" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearDigits() {
        _hasBits0 &= ~2;
      }

      /// <summary>Field number for the "type" field.</summary>
      public const int TypeFieldNumber = 6;
      private readonly static global::Payload.Types.OtpType TypeDefaultValue = global::Payload.Types.OtpType.Unspecified;

      private global::Payload.Types.OtpType type_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::Payload.Types.OtpType Type {
        get { if ((_hasBits0 & 4) != 0) { return type_; } else { return TypeDefaultValue; } }
        set {
          _hasBits0 |= 4;
          type_ = value;
        }
      }
      /// <summary>Gets whether the "type" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasType {
        get { return (_hasBits0 & 4) != 0; }
      }
      /// <summary>Clears the value of the "type" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearType() {
        _hasBits0 &= ~4;
      }

      /// <summary>Field number for the "counter" field.</summary>
      public const int CounterFieldNumber = 7;
      private readonly static long CounterDefaultValue = 0L;

      private long counter_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public long Counter {
        get { if ((_hasBits0 & 8) != 0) { return counter_; } else { return CounterDefaultValue; } }
        set {
          _hasBits0 |= 8;
          counter_ = value;
        }
      }
      /// <summary>Gets whether the "counter" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasCounter {
        get { return (_hasBits0 & 8) != 0; }
      }
      /// <summary>Clears the value of the "counter" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearCounter() {
        _hasBits0 &= ~8;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as OtpParameters);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(OtpParameters other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (Secret != other.Secret) return false;
        if (Name != other.Name) return false;
        if (Issuer != other.Issuer) return false;
        if (Algorithm != other.Algorithm) return false;
        if (Digits != other.Digits) return false;
        if (Type != other.Type) return false;
        if (Counter != other.Counter) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (HasSecret) hash ^= Secret.GetHashCode();
        if (HasName) hash ^= Name.GetHashCode();
        if (HasIssuer) hash ^= Issuer.GetHashCode();
        if (HasAlgorithm) hash ^= Algorithm.GetHashCode();
        if (HasDigits) hash ^= Digits.GetHashCode();
        if (HasType) hash ^= Type.GetHashCode();
        if (HasCounter) hash ^= Counter.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (HasSecret) {
          output.WriteRawTag(10);
          output.WriteBytes(Secret);
        }
        if (HasName) {
          output.WriteRawTag(18);
          output.WriteString(Name);
        }
        if (HasIssuer) {
          output.WriteRawTag(26);
          output.WriteString(Issuer);
        }
        if (HasAlgorithm) {
          output.WriteRawTag(32);
          output.WriteEnum((int) Algorithm);
        }
        if (HasDigits) {
          output.WriteRawTag(40);
          output.WriteEnum((int) Digits);
        }
        if (HasType) {
          output.WriteRawTag(48);
          output.WriteEnum((int) Type);
        }
        if (HasCounter) {
          output.WriteRawTag(56);
          output.WriteInt64(Counter);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (HasSecret) {
          output.WriteRawTag(10);
          output.WriteBytes(Secret);
        }
        if (HasName) {
          output.WriteRawTag(18);
          output.WriteString(Name);
        }
        if (HasIssuer) {
          output.WriteRawTag(26);
          output.WriteString(Issuer);
        }
        if (HasAlgorithm) {
          output.WriteRawTag(32);
          output.WriteEnum((int) Algorithm);
        }
        if (HasDigits) {
          output.WriteRawTag(40);
          output.WriteEnum((int) Digits);
        }
        if (HasType) {
          output.WriteRawTag(48);
          output.WriteEnum((int) Type);
        }
        if (HasCounter) {
          output.WriteRawTag(56);
          output.WriteInt64(Counter);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (HasSecret) {
          size += 1 + pb::CodedOutputStream.ComputeBytesSize(Secret);
        }
        if (HasName) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
        }
        if (HasIssuer) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(Issuer);
        }
        if (HasAlgorithm) {
          size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Algorithm);
        }
        if (HasDigits) {
          size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Digits);
        }
        if (HasType) {
          size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
        }
        if (HasCounter) {
          size += 1 + pb::CodedOutputStream.ComputeInt64Size(Counter);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(OtpParameters other) {
        if (other == null) {
          return;
        }
        if (other.HasSecret) {
          Secret = other.Secret;
        }
        if (other.HasName) {
          Name = other.Name;
        }
        if (other.HasIssuer) {
          Issuer = other.Issuer;
        }
        if (other.HasAlgorithm) {
          Algorithm = other.Algorithm;
        }
        if (other.HasDigits) {
          Digits = other.Digits;
        }
        if (other.HasType) {
          Type = other.Type;
        }
        if (other.HasCounter) {
          Counter = other.Counter;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 10: {
              Secret = input.ReadBytes();
              break;
            }
            case 18: {
              Name = input.ReadString();
              break;
            }
            case 26: {
              Issuer = input.ReadString();
              break;
            }
            case 32: {
              Algorithm = (global::Payload.Types.Algorithm) input.ReadEnum();
              break;
            }
            case 40: {
              Digits = (global::Payload.Types.DigitCount) input.ReadEnum();
              break;
            }
            case 48: {
              Type = (global::Payload.Types.OtpType) input.ReadEnum();
              break;
            }
            case 56: {
              Counter = input.ReadInt64();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 10: {
              Secret = input.ReadBytes();
              break;
            }
            case 18: {
              Name = input.ReadString();
              break;
            }
            case 26: {
              Issuer = input.ReadString();
              break;
            }
            case 32: {
              Algorithm = (global::Payload.Types.Algorithm) input.ReadEnum();
              break;
            }
            case 40: {
              Digits = (global::Payload.Types.DigitCount) input.ReadEnum();
              break;
            }
            case 48: {
              Type = (global::Payload.Types.OtpType) input.ReadEnum();
              break;
            }
            case 56: {
              Counter = input.ReadInt64();
              break;
            }
          }
        }
      }
      #endif

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
