name: master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            buildprops:
              - 'Directory.Build.props'

      - name: NuGet restore
        run: nuget restore authenticator.sln

      - name: Build
        run: msbuild authenticator.sln -p:Configuration=Release -m

      - name: Publish build
        uses: actions/upload-artifact@v4
        with:
          name: authenticator
          path: |
            bin/Authenticator