name: master

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: nuget/setup-nuget@d105a947828025cd7a980103c35ba2bfae586d0f # v2.0.2
      - uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
        with:
          msbuild-architecture: x64

      - name: NuGet restore
        run: nuget restore authenticator.sln

      - name: Build
        run: msbuild authenticator.sln -p:Configuration=Release -m

      # - name: Publish build
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: authenticator
      #     path: |
      #       Authenticator/bin
